// GENERATED by the table in this repo's history (see GAME_DESIGN.md §5.1 for
// the numbers and their reasons); state layout documented in weapons/base.zs.
// Numbers: damage is Doom-style N*random(a,b); spreads in degrees; Kick is the
// recoil pitch in degrees; reload tics scale with the gun's size.

// All alien weapons draw from one universal ammo: AlienEnergy.

// Harvester blade: slot 1 alternative. Fire = two-hit combo, alt = heavy lunge.
class CCA_HarvesterBlade : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 1;
		Weapon.SelectionOrder 3600;
		CCAWeapon.MagSize 0;
		CCAWeapon.ADSZoom 0;
		CCAWeapon.CanDual 0;
		CCAWeapon.Reticle 0;
		Tag "$C51_TAG_BLADE";
		Inventory.PickupMessage "$C51_GOT_BLADE";
		+WEAPON.MELEEWEAPON
	}
	States
	{
	Spawn:
		WABL A -1;
		Stop;
	Select:
		ABLD A 1 CCA_Select;
		Loop;
	Deselect:
		ABLD A 1 CCA_Deselect;
		Loop;
	Ready:
		ABLD A 1 CCA_Ready;
		Loop;
	Fire:
		ABLD B 3;
		ABLD C 2 CCA_Melee(88, 5, 4, 10);
		ABLD D 4;
		ABLD E 3;
		ABLD F 2 CCA_Melee(88, 5, 4, 10);
		ABLD G 5;
		ABLD A 3;
		Goto Ready;
	AltFire:
		ABLD E 4;
		ABLD F 3 CCA_Melee(96, 9, 4, 10, true);
		ABLD G 10;
		ABLD A 4;
		Goto Ready;
	}
}

class CCA_Stinger : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 2;
		Weapon.SelectionOrder 1800;
		Weapon.AmmoType1 "AlienEnergy";
		Weapon.AmmoGive1 30;
		CCAWeapon.MagSize 0;
		CCAWeapon.Damage 0, 0, 0;
		CCAWeapon.Pellets 1;
		CCAWeapon.SpreadHip 1.2;
		CCAWeapon.SpreadADS 0.2;
		CCAWeapon.ADSZoom 1.35;
		CCAWeapon.Kick 0.9;
		CCAWeapon.FireSound "weapons/stinger";
		CCAWeapon.SemiAuto 1;
		CCAWeapon.Reticle 5;
		Tag "$C51_TAG_STINGER";
		Inventory.PickupMessage "$C51_GOT_STINGER";
		CCAWeapon.Projectile "CCAStingerBolt";
		CCAWeapon.AmmoPerShot 1;
	}
	States
	{
	Spawn:
		WAST A -1;
		Stop;
	Select:
		ASTG A 1 CCA_Select;
		Loop;
	Deselect:
		ASTG A 1 CCA_Deselect;
		Loop;
	Ready:
		ASTG A 1 CCA_Ready;
		Loop;
	Fire:
		ASTG B 1 CCA_Fire;
		ASTG C 6;
		ASTG A 2;
		Goto Ready;
	Flash:
		ASTG X 2 Bright;
		Stop;
	ADSIn:
		ASTG O 2;
		Goto ADSReady;
	ADSReady:
		ASTG L 1 CCA_Ready;
		Loop;
	ADSFire:
		ASTG M 1 CCA_Fire;
		ASTG N 6;
		ASTG L 2;
		Goto ADSReady;
	ADSFlash:
		ASTG Y 2 Bright;
		Stop;
	ADSOut:
		ASTG O 2;
		Goto Ready;
	Reload:
		Goto Ready;
	LeftReload:
		Goto LeftReady;
	LeftReady:
		ASTG A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		ASTG B 1 CCA_LeftFire;
		ASTG C 6;
		ASTG A 2;
		Goto LeftReady;
	LeftFlash:
		ASTG X 2 Bright;
		Stop;
	}
}

class CCA_Scatter : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 3;
		Weapon.SelectionOrder 1200;
		Weapon.AmmoType1 "AlienEnergy";
		Weapon.AmmoGive1 30;
		CCAWeapon.MagSize 0;
		CCAWeapon.Damage 0, 0, 0;
		CCAWeapon.Pellets 10;
		CCAWeapon.SpreadHip 6.0;
		CCAWeapon.SpreadADS 4.0;
		CCAWeapon.ADSZoom 1.2;
		CCAWeapon.Kick 3.0;
		CCAWeapon.FireSound "weapons/scatter";
		CCAWeapon.SemiAuto 1;
		CCAWeapon.Reticle 2;
		Tag "$C51_TAG_SCATTER";
		Inventory.PickupMessage "$C51_GOT_SCATTER";
		CCAWeapon.Projectile "CCAScatterPellet";
		CCAWeapon.AmmoPerShot 4;
	}
	States
	{
	Spawn:
		WASC A -1;
		Stop;
	Select:
		ASCT A 1 CCA_Select;
		Loop;
	Deselect:
		ASCT A 1 CCA_Deselect;
		Loop;
	Ready:
		ASCT A 1 CCA_Ready;
		Loop;
	Fire:
		ASCT B 1 CCA_Fire;
		ASCT B 3;
		ASCT C 10;
		ASCT A 10;
		Goto Ready;
	Flash:
		ASCT X 2 Bright;
		Stop;
	ADSIn:
		ASCT O 2;
		Goto ADSReady;
	ADSReady:
		ASCT L 1 CCA_Ready;
		Loop;
	ADSFire:
		ASCT M 1 CCA_Fire;
		ASCT M 3;
		ASCT N 10;
		ASCT L 10;
		Goto ADSReady;
	ADSFlash:
		ASCT Y 2 Bright;
		Stop;
	ADSOut:
		ASCT O 2;
		Goto Ready;
	Reload:
		Goto Ready;
	LeftReload:
		Goto LeftReady;
	LeftReady:
		ASCT A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		ASCT B 1 CCA_LeftFire;
		ASCT B 3;
		ASCT C 10;
		ASCT A 10;
		Goto LeftReady;
	LeftFlash:
		ASCT X 2 Bright;
		Stop;
	}
}

class CCA_PlasmaSMG : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 4;
		Weapon.SelectionOrder 650;
		Weapon.AmmoType1 "AlienEnergy";
		Weapon.AmmoGive1 40;
		CCAWeapon.MagSize 0;
		CCAWeapon.Damage 0, 0, 0;
		CCAWeapon.Pellets 1;
		CCAWeapon.SpreadHip 2.2;
		CCAWeapon.SpreadADS 0.8;
		CCAWeapon.ADSZoom 1.3;
		CCAWeapon.Kick 0.45;
		CCAWeapon.FireSound "weapons/plasmasmg";
		CCAWeapon.SemiAuto 0;
		CCAWeapon.Reticle 6;
		Tag "$C51_TAG_PLASMA";
		Inventory.PickupMessage "$C51_GOT_PLASMA";
		CCAWeapon.Projectile "CCAPlasmaBolt";
		CCAWeapon.AmmoPerShot 1;
		CCAWeapon.HeatPerShot 6;
	}
	States
	{
	Spawn:
		WAPS A -1;
		Stop;
	Select:
		APSM A 1 CCA_Select;
		Loop;
	Deselect:
		APSM A 1 CCA_Deselect;
		Loop;
	Ready:
		APSM A 1 CCA_Ready;
		Loop;
	Fire:
		APSM B 1 CCA_Fire;
		APSM C 2 CCA_HeatCheck;
		Goto Ready;
	Flash:
		APSM X 2 Bright;
		Stop;
	ADSIn:
		APSM O 2;
		Goto ADSReady;
	ADSReady:
		APSM L 1 CCA_Ready;
		Loop;
	ADSFire:
		APSM M 1 CCA_Fire;
		APSM N 2 CCA_HeatCheck;
		Goto ADSReady;
	ADSFlash:
		APSM Y 2 Bright;
		Stop;
	ADSOut:
		APSM O 2;
		Goto Ready;
	Vent:
		APSM D 3;
		APSM E 3;
		APSM F 4;
		APSM G 5;
		APSM H 6;
		APSM I 5;
		APSM J 4;
		APSM K 3 CCA_VentDone;
		Goto Ready;
	Reload:
		Goto Ready;
	LeftReload:
		Goto LeftReady;
	LeftReady:
		APSM A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		APSM B 1 CCA_LeftFire;
		APSM C 2;
		Goto LeftReady;
	LeftFlash:
		APSM X 2 Bright;
		Stop;
	}
}


// The Singularity: charge, then a slow black-violet ball that tears at
// everything in view when it bursts (Doom's BFG spray). 40 energy a shot.
class CCA_Singularity : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 7;
		Weapon.SelectionOrder 2800;
		Weapon.AmmoType1 "AlienEnergy";
		Weapon.AmmoGive1 80;
		CCAWeapon.MagSize 0;
		CCAWeapon.AmmoPerShot 40;
		CCAWeapon.ADSZoom 0;
		CCAWeapon.CanDual 0;
		CCAWeapon.Projectile "CCASingularityBall";
		CCAWeapon.SpreadHip 0;
		CCAWeapon.Kick 4;
		CCAWeapon.FireSound "weapons/singfire";
		CCAWeapon.SemiAuto 1;
		CCAWeapon.Reticle 7;
		Tag "$C51_TAG_SING";
		Inventory.PickupMessage "$C51_GOT_SING";
	}
	States
	{
	Spawn:
		WSNG A -1;
		Stop;
	Select:
		SNGL A 1 CCA_Select;
		Loop;
	Deselect:
		SNGL A 1 CCA_Deselect;
		Loop;
	Ready:
		SNGL A 1 CCA_Ready;
		Loop;
	Fire:
		SNGL B 5 A_StartSound("weapons/singcharge", CHAN_WEAPON);
		SNGL C 5;
		SNGL D 5;
		SNGL E 5 Bright;
		SNGL F 5 Bright;
		SNGL G 4 Bright CCA_Fire;
		SNGL H 8;
		SNGL I 8;
		Goto Ready;
	Flash:
		TNT1 A 1;
		Stop;
	}
}

// ---------------------------------------------------------------- projectiles
class CCAStingerBolt : Actor
{
	Default { Radius 4; Height 6; Speed 55; DamageFunction (6 * random(2, 4)); Projectile; +RANDOMIZE; RenderStyle "Add"; Scale 0.5; DeathSound "weapons/boltimpact"; Obituary "$C51_OB_STINGER"; }
	States
	{
	Spawn:
		ASTB AB 2 Bright A_SpawnItemEx("CCABoltTrail", flags: SXF_CLIENTSIDE);
		Loop;
	Death:
		ASTB CDE 3 Bright;
		Stop;
	}
}
class CCABoltTrail : Actor
{
	Default { +NOINTERACTION; RenderStyle "Add"; Alpha 0.5; Scale 0.3; }
	States { Spawn: ASTB B 1 Bright A_FadeOut(0.12); Loop; }
}
class CCAScatterPellet : Actor
{
	Default { Radius 3; Height 4; Speed 42; DamageFunction (4 * random(1, 3)); Projectile; RenderStyle "Add"; Scale 0.45; PainChance 128; Obituary "$C51_OB_SCATTER"; }
	override int DoSpecialDamage(Actor target, int damage, Name damagetype)
	{
		// stagger: plasma pellets make things flinch far more often than bullets
		if (target && target.bIsMonster && random(0, 255) < 96) target.TriggerPainChance('None', true);
		return damage;
	}
	States
	{
	Spawn:
		ASCP A 1 Bright;
		Loop;
	Death:
		ASCP BC 3 Bright;
		Stop;
	}
}
class CCAPlasmaBolt : Actor
{
	Default { Radius 4; Height 6; Speed 48; DamageFunction (5 * random(1, 3)); Projectile; RenderStyle "Add"; Scale 0.5; DeathSound "weapons/plasmahit"; Obituary "$C51_OB_PLASMA"; }
	States
	{
	Spawn:
		APLS AB 2 Bright;
		Loop;
	Death:
		APLS CDE 3 Bright;
		Stop;
	}
}
class CCASingularityBall : Actor
{
	Default { Radius 13; Height 8; Speed 22; Damage 100; Projectile; +RANDOMIZE; RenderStyle "Add"; Scale 0.8; DeathSound "weapons/singboom"; Obituary "$C51_OB_SING"; }
	States
	{
	Spawn:
		SNGB AB 4 Bright;
		Loop;
	Death:
		SNGB C 8 Bright;
		SNGB D 8 Bright;
		SNGB E 8 Bright A_BFGSpray("CCASingularitySpray");
		SNGB F 8 Bright;
		SNGB G 8 Bright;
		SNGB H 6 Bright;
		Stop;
	}
}
class CCASingularitySpray : Actor
{
	Default { +NOBLOCKMAP; +NOGRAVITY; RenderStyle "Add"; Alpha 0.75; Scale 0.6; }
	States { Spawn: SNGB CDEF 4 Bright; Stop; }
}
