// GENERATED by the table in this repo's history (see GAME_DESIGN.md §5.1 for
// the numbers and their reasons); state layout documented in weapons/base.zs.
// Numbers: damage is Doom-style N*random(a,b); spreads in degrees; Kick is the
// recoil pitch in degrees; reload tics scale with the gun's size.

// Combat knife: slot 1. Fire = slash, alt-fire = stab lunge (no ADS, no dual).
class CCA_Knife : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 1;
		Weapon.SelectionOrder 3700;
		CCAWeapon.MagSize 0;
		CCAWeapon.ADSZoom 0;
		CCAWeapon.CanDual 0;
		CCAWeapon.Reticle 0;
		Tag "$C51_TAG_KNIFE";
		+WEAPON.MELEEWEAPON
	}
	States
	{
	Spawn:
		MELE A -1;
		Stop;
	Select:
		KNIF A 1 CCA_Select;
		Loop;
	Deselect:
		KNIF A 1 CCA_Deselect;
		Loop;
	Ready:
		KNIF A 1 CCA_Ready;
		Loop;
	Fire:
		KNIF B 2;
		KNIF C 2 CCA_Melee(72, 3, 4, 10);
		KNIF D 3;
		KNIF E 4;
		KNIF A 3;
		Goto Ready;
	AltFire:
		KNIF F 3;
		KNIF G 3 CCA_Melee(84, 5, 4, 10, true);
		KNIF H 8;
		KNIF A 4;
		Goto Ready;
	}
}

class CCA_Pistol : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 2;
		Weapon.SelectionOrder 1900;
		Weapon.AmmoType1 "Ammo9mm";
		Weapon.AmmoGive1 15;
		CCAWeapon.MagSize 15;
		CCAWeapon.Damage 5, 2, 3;
		CCAWeapon.Pellets 1;
		CCAWeapon.SpreadHip 1.6;
		CCAWeapon.SpreadADS 0.2;
		CCAWeapon.ADSZoom 1.35;
		CCAWeapon.Kick 1.2;
		CCAWeapon.FireSound "weapons/pistol";
		CCAWeapon.SemiAuto 1;
		CCAWeapon.Reticle 1;
		Tag "$C51_TAG_PISTOL";
		Inventory.PickupMessage "$C51_GOT_PISTOL";
		CCAWeapon.Casing "CCACasing";
	}
	States
	{
	Spawn:
		WP9M A -1;
		Stop;
	Select:
		P9MM A 1 CCA_Select;
		Loop;
	Deselect:
		P9MM A 1 CCA_Deselect;
		Loop;
	Ready:
		P9MM A 1 CCA_Ready;
		Loop;
	Fire:
		P9MM B 1 CCA_Fire;
		P9MM B 1;
		P9MM C 3;
		P9MM A 2;
		Goto Ready;
	Flash:
		P9MM X 2 Bright;
		Stop;
	ADSIn:
		P9MM O 2;
		Goto ADSReady;
	ADSReady:
		P9MM L 1 CCA_Ready;
		Loop;
	ADSFire:
		P9MM M 1 CCA_Fire;
		P9MM M 1;
		P9MM N 3;
		P9MM L 2;
		Goto ADSReady;
	ADSFlash:
		P9MM Y 2 Bright;
		Stop;
	ADSOut:
		P9MM O 2;
		Goto Ready;
	Reload:
		P9MM D 4 CCA_ReloadStart;
		P9MM E 4;
		P9MM F 5;
		P9MM G 5;
		P9MM H 4 CCA_ReloadFill;
		P9MM I 4 CCA_Rack;
		P9MM J 3;
		P9MM K 3;
		Goto Ready;
	LeftReload:
		P9MM D 4;
		P9MM E 4;
		P9MM F 5;
		P9MM G 5;
		P9MM H 4 CCA_LeftFill;
		P9MM I 4;
		P9MM J 3;
		P9MM K 3;
		Goto LeftReady;
	LeftReady:
		P9MM A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		P9MM B 1 CCA_LeftFire;
		P9MM B 1;
		P9MM C 3;
		P9MM A 2;
		Goto LeftReady;
	LeftFlash:
		P9MM X 2 Bright;
		Stop;
	}
}

class CCA_Shotgun : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 3;
		Weapon.SelectionOrder 1300;
		Weapon.AmmoType1 "Ammo12g";
		Weapon.AmmoGive1 8;
		CCAWeapon.MagSize 7;
		CCAWeapon.Damage 5, 1, 3;
		CCAWeapon.Pellets 8;
		CCAWeapon.SpreadHip 5.6;
		CCAWeapon.SpreadADS 3.8;
		CCAWeapon.ADSZoom 1.2;
		CCAWeapon.Kick 3.5;
		CCAWeapon.FireSound "weapons/shotgun";
		CCAWeapon.SemiAuto 1;
		CCAWeapon.Reticle 2;
		Tag "$C51_TAG_SHOTGUN";
		Inventory.PickupMessage "$C51_GOT_SHOTGUN";
	}
	States
	{
	Spawn:
		WSHT A -1;
		Stop;
	Select:
		SHOT A 1 CCA_Select;
		Loop;
	Deselect:
		SHOT A 1 CCA_Deselect;
		Loop;
	Ready:
		SHOT A 1 CCA_Ready;
		Loop;
	Fire:
		SHOT B 1 CCA_Fire;
		SHOT B 3;
		SHOT C 6;
		SHOT G 6 CCA_PumpShell;
		SHOT H 6;
		SHOT A 6;
		Goto Ready;
	Flash:
		SHOT X 2 Bright;
		Stop;
	ADSIn:
		SHOT O 2;
		Goto ADSReady;
	ADSReady:
		SHOT L 1 CCA_Ready;
		Loop;
	ADSFire:
		SHOT M 1 CCA_Fire;
		SHOT M 3;
		SHOT N 8;
		SHOT L 16 CCA_PumpShell;
		Goto ADSReady;
	ADSFlash:
		SHOT Y 2 Bright;
		Stop;
	ADSOut:
		SHOT O 2;
		Goto Ready;
	Reload:
		SHOT D 5 CCA_ReloadStart;
	ReloadLoop:
		SHOT E 4;
		SHOT F 5 CCA_InsertShell;
		SHOT F 0 CCA_ShellCheck("ReloadEnd");
		Loop;
	ReloadEnd:
		SHOT G 4 CCA_PumpShell;
		SHOT H 5;
		Goto Ready;
	LeftReload:
		SHOT D 5;
	LeftReloadLoop:
		SHOT E 4;
		SHOT F 5 CCA_InsertShell(true);
		SHOT F 0 CCA_ShellCheck("LeftReloadEnd", true);
		Loop;
	LeftReloadEnd:
		SHOT G 4;
		SHOT H 5;
		Goto LeftReady;
	LeftReady:
		SHOT A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		SHOT B 1 CCA_LeftFire;
		SHOT B 3;
		SHOT C 6;
		SHOT G 6;
		SHOT H 6;
		SHOT A 6;
		Goto LeftReady;
	LeftFlash:
		SHOT X 2 Bright;
		Stop;
	}
}

class CCA_SMG : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 4;
		Weapon.SelectionOrder 700;
		Weapon.AmmoType1 "Ammo9mm";
		Weapon.AmmoGive1 32;
		CCAWeapon.MagSize 32;
		CCAWeapon.Damage 4, 1, 3;
		CCAWeapon.Pellets 1;
		CCAWeapon.SpreadHip 2.6;
		CCAWeapon.SpreadADS 0.9;
		CCAWeapon.ADSZoom 1.3;
		CCAWeapon.Kick 0.5;
		CCAWeapon.FireSound "weapons/smg";
		CCAWeapon.SemiAuto 0;
		CCAWeapon.Reticle 3;
		Tag "$C51_TAG_SMG";
		Inventory.PickupMessage "$C51_GOT_SMG";
		CCAWeapon.Casing "CCACasing";
	}
	States
	{
	Spawn:
		WSMG A -1;
		Stop;
	Select:
		SMG9 A 1 CCA_Select;
		Loop;
	Deselect:
		SMG9 A 1 CCA_Deselect;
		Loop;
	Ready:
		SMG9 A 1 CCA_Ready;
		Loop;
	Fire:
		SMG9 B 1 CCA_Fire;
		SMG9 C 2;
		Goto Ready;
	Flash:
		SMG9 X 2 Bright;
		Stop;
	ADSIn:
		SMG9 O 2;
		Goto ADSReady;
	ADSReady:
		SMG9 L 1 CCA_Ready;
		Loop;
	ADSFire:
		SMG9 M 1 CCA_Fire;
		SMG9 N 2;
		Goto ADSReady;
	ADSFlash:
		SMG9 Y 2 Bright;
		Stop;
	ADSOut:
		SMG9 O 2;
		Goto Ready;
	Reload:
		SMG9 D 4 CCA_ReloadStart;
		SMG9 E 4;
		SMG9 F 6;
		SMG9 G 6;
		SMG9 H 4 CCA_ReloadFill;
		SMG9 I 4 CCA_Rack;
		SMG9 J 3;
		SMG9 K 3;
		Goto Ready;
	LeftReload:
		SMG9 D 4;
		SMG9 E 4;
		SMG9 F 6;
		SMG9 G 6;
		SMG9 H 4 CCA_LeftFill;
		SMG9 I 4;
		SMG9 J 3;
		SMG9 K 3;
		Goto LeftReady;
	LeftReady:
		SMG9 A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		SMG9 B 1 CCA_LeftFire;
		SMG9 C 2;
		Goto LeftReady;
	LeftFlash:
		SMG9 X 2 Bright;
		Stop;
	}
}

class CCA_AssaultRifle : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 5;
		Weapon.SelectionOrder 600;
		Weapon.AmmoType1 "Ammo556";
		Weapon.AmmoGive1 30;
		CCAWeapon.MagSize 30;
		CCAWeapon.Damage 5, 2, 3;
		CCAWeapon.Pellets 1;
		CCAWeapon.SpreadHip 2.2;
		CCAWeapon.SpreadADS 0.5;
		CCAWeapon.ADSZoom 1.45;
		CCAWeapon.Kick 0.7;
		CCAWeapon.FireSound "weapons/rifle";
		CCAWeapon.SemiAuto 0;
		CCAWeapon.Reticle 3;
		Tag "$C51_TAG_RIFLE";
		Inventory.PickupMessage "$C51_GOT_RIFLE";
		CCAWeapon.Casing "CCACasing";
	}
	States
	{
	Spawn:
		WARF A -1;
		Stop;
	Select:
		ARFL A 1 CCA_Select;
		Loop;
	Deselect:
		ARFL A 1 CCA_Deselect;
		Loop;
	Ready:
		ARFL A 1 CCA_Ready;
		Loop;
	Fire:
		ARFL B 1 CCA_Fire;
		ARFL C 3;
		Goto Ready;
	Flash:
		ARFL X 2 Bright;
		Stop;
	ADSIn:
		ARFL O 2;
		Goto ADSReady;
	ADSReady:
		ARFL L 1 CCA_Ready;
		Loop;
	ADSFire:
		ARFL M 1 CCA_Fire;
		ARFL N 3;
		Goto ADSReady;
	ADSFlash:
		ARFL Y 2 Bright;
		Stop;
	ADSOut:
		ARFL O 2;
		Goto Ready;
	Reload:
		ARFL D 5 CCA_ReloadStart;
		ARFL E 5;
		ARFL F 6;
		ARFL G 6;
		ARFL H 5 CCA_ReloadFill;
		ARFL I 5 CCA_Rack;
		ARFL J 4;
		ARFL K 4;
		Goto Ready;
	LeftReload:
		ARFL D 5;
		ARFL E 5;
		ARFL F 6;
		ARFL G 6;
		ARFL H 5 CCA_LeftFill;
		ARFL I 5;
		ARFL J 4;
		ARFL K 4;
		Goto LeftReady;
	LeftReady:
		ARFL A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		ARFL B 1 CCA_LeftFire;
		ARFL C 3;
		Goto LeftReady;
	LeftFlash:
		ARFL X 2 Bright;
		Stop;
	}
}

class CCA_BattleRifle : CCAWeapon
{
	Default
	{
		Weapon.SlotNumber 6;
		Weapon.SelectionOrder 650;
		Weapon.AmmoType1 "Ammo762";
		Weapon.AmmoGive1 20;
		CCAWeapon.MagSize 20;
		CCAWeapon.Damage 6, 2, 4;
		CCAWeapon.Pellets 1;
		CCAWeapon.SpreadHip 1.8;
		CCAWeapon.SpreadADS 0.12;
		CCAWeapon.ADSZoom 2.3;
		CCAWeapon.Kick 1.1;
		CCAWeapon.FireSound "weapons/battlerifle";
		CCAWeapon.SemiAuto 1;
		CCAWeapon.Reticle 4;
		Tag "$C51_TAG_BATTLE";
		Inventory.PickupMessage "$C51_GOT_BATTLE";
		CCAWeapon.Casing "CCACasing";
	}
	States
	{
	Spawn:
		WBRF A -1;
		Stop;
	Select:
		BRFL A 1 CCA_Select;
		Loop;
	Deselect:
		BRFL A 1 CCA_Deselect;
		Loop;
	Ready:
		BRFL A 1 CCA_Ready;
		Loop;
	Fire:
		BRFL B 1 CCA_Fire;
		BRFL C 1;
		BRFL B 1 CCA_Fire;
		BRFL C 1;
		BRFL B 1 CCA_Fire;
		BRFL C 3;
		BRFL A 8;
		Goto Ready;
	Flash:
		BRFL X 2 Bright;
		Stop;
	ADSIn:
		BRFL O 2;
		Goto ADSReady;
	ADSReady:
		BRFL L 1 CCA_Ready;
		Loop;
	ADSFire:
		BRFL M 1 CCA_Fire;
		BRFL N 1;
		BRFL M 1 CCA_Fire;
		BRFL N 1;
		BRFL M 1 CCA_Fire;
		BRFL N 3;
		BRFL L 8;
		Goto ADSReady;
	ADSFlash:
		BRFL Y 2 Bright;
		Stop;
	ADSOut:
		BRFL O 2;
		Goto Ready;
	Reload:
		BRFL D 5 CCA_ReloadStart;
		BRFL E 5;
		BRFL F 6;
		BRFL G 6;
		BRFL H 5 CCA_ReloadFill;
		BRFL I 5 CCA_Rack;
		BRFL J 4;
		BRFL K 4;
		Goto Ready;
	LeftReload:
		BRFL D 5;
		BRFL E 5;
		BRFL F 6;
		BRFL G 6;
		BRFL H 5 CCA_LeftFill;
		BRFL I 5;
		BRFL J 4;
		BRFL K 4;
		Goto LeftReady;
	LeftReady:
		BRFL A 1 CCA_LeftReady;
		Loop;
	LeftFire:
		BRFL B 1 CCA_LeftFire;
		BRFL C 1;
		BRFL B 1 CCA_LeftFire;
		BRFL C 1;
		BRFL B 1 CCA_LeftFire;
		BRFL C 3;
		BRFL A 8;
		Goto LeftReady;
	LeftFlash:
		BRFL X 2 Bright;
		Stop;
	}
}


extend class CCAWeapon
{
	// pump sound + a red shell out of the port
	action void CCA_PumpShell()
	{
		A_StartSound("weapons/pump", CHAN_WEAPON);
		let c = Spawn("CCAShellCasing", pos + (0, 0, player ? player.viewheight - 10 : 30) + (AngleToVector(angle - 60, 10), 0));
		if (c) { c.Vel3DFromAngle(frandom(3, 5), angle - 100 + frandom(-15, 15), frandom(-50, -30)); c.Vel += Vel; }
	}
}
