// Level model -> UDMF TEXTMAP (namespace "zdoom": Hexen-style specials, ZDoom extensions).
const vkey = (p) => `${p[0]},${p[1]}`;

function fmtNum(n) { return Number.isInteger(n) ? `${n}.0` : String(n); }
function q(s) { return `"${String(s).replace(/"/g, '\\"')}"`; }

export function writeTextmap(lv) {
  const out = [];
  out.push('// Generated by tools/mapc.mjs from ' + lv.file.replace(/^.*maps-src\//, 'maps-src/') + ' - edit the source, not this.');
  out.push('namespace = "zdoom";', '');
  // vertices
  const vIndex = new Map(), verts = [];
  const vid = (p) => { const k = vkey(p); if (!vIndex.has(k)) { vIndex.set(k, verts.length); verts.push(p); } return vIndex.get(k); };
  for (const l of lv.lines) { vid(l.v1); vid(l.v2); }
  // sectors in output order = their ids
  const sides = [];
  const sideOf = (s) => { sides.push(s); return sides.length - 1; };
  const lineBlocks = [];
  for (const l of lv.lines) {
    const f = sideOf(l.front), b = l.back ? sideOf(l.back) : -1;
    const kv = [`v1 = ${vid(l.v1)};`, `v2 = ${vid(l.v2)};`, `sidefront = ${f};`];
    if (b >= 0) kv.push(`sideback = ${b};`);
    for (const [k, v] of Object.entries(l.flags)) if (v) kv.push(`${k} = true;`);
    if (l.special) {
      kv.push(`special = ${l.special};`);
      l.args.forEach((a, i) => { if (a) kv.push(`arg${i} = ${a | 0};`); });
    }
    if (l.id) kv.push(`id = ${l.id};`);
    lineBlocks.push(`linedef // ${l.role}\n{\n${kv.map((s) => '  ' + s).join('\n')}\n}`);
  }
  verts.forEach((p) => out.push(`vertex { x = ${fmtNum(p[0])}; y = ${fmtNum(p[1])}; }`));
  out.push('');
  out.push(...lineBlocks, '');
  for (const s of sides) {
    const kv = [`sector = ${s.sector.id};`];
    if (s.top && s.top !== '-') kv.push(`texturetop = ${q(s.top)};`);
    if (s.mid && s.mid !== '-') kv.push(`texturemiddle = ${q(s.mid)};`);
    if (s.bottom && s.bottom !== '-') kv.push(`texturebottom = ${q(s.bottom)};`);
    if (s.offsetx) kv.push(`offsetx = ${s.offsetx};`);
    if (s.offsety) kv.push(`offsety = ${s.offsety};`);
    out.push(`sidedef { ${kv.join(' ')} }`);
  }
  out.push('');
  for (const s of lv.sectors) {
    const p = s.p || {};
    const kv = [
      `heightfloor = ${s.floor | 0};`, `heightceiling = ${s.ceil | 0};`,
      `texturefloor = ${q(s.ff)};`, `textureceiling = ${q(s.cf)};`, `lightlevel = ${Math.max(0, Math.min(255, s.light | 0))};`,
    ];
    let special = 0;
    // secret doors only look like wall; the room behind them carries `secret`
    if (p.secret && s.kind !== 'door') special |= 1024;
    if (special) kv.push(`special = ${special};`);
    const tags = [...new Set(s.tags)];
    if (tags.length) kv.push(`id = ${tags[0]};`);
    if (tags.length > 1) kv.push(`moreids = ${q(tags.slice(1).join(' '))};`);
    if (p.color && p.color.color !== undefined) kv.push(`lightcolor = ${p.color.color};`);
    if (p.fade && p.fade.color !== undefined) kv.push(`fadecolor = ${p.fade.color};`);
    if (p.damage) { kv.push(`damageamount = ${p.damage | 0};`, `damageinterval = ${p.dmginterval || 32};`); if (p.dmgtype) kv.push(`damagetype = ${q(p.dmgtype)};`); }
    if (p.seq) kv.push(`soundsequence = ${q(p.seq)};`);
    if (p.lightfloor) kv.push(`lightfloor = ${p.lightfloor | 0};`);
    if (p.lightceiling) kv.push(`lightceiling = ${p.lightceiling | 0};`);
    if (p.glow && p.glow.color !== undefined) kv.push(`floorglowcolor = ${p.glow.color};`, `floorglowheight = ${p.glowheight || 64}.0;`);
    if (p.ceilglow && p.ceilglow.color !== undefined) kv.push(`ceilingglowcolor = ${p.ceilglow.color};`, `ceilingglowheight = ${p.ceilglowheight || 64}.0;`);
    if (p.hidden) kv.push('hidden = true;');
    out.push(`sector // ${s.id} '${s.char}' ${s.kind}\n{\n${kv.map((x) => '  ' + x).join('\n')}\n}`);
  }
  out.push('');
  for (const t of lv.things) {
    const kv = [`x = ${fmtNum(t.x)};`, `y = ${fmtNum(t.y)};`, `type = ${t.ed};`, `angle = ${t.angle | 0};`];
    if (t.height) kv.push(`height = ${fmtNum(t.height)};`);
    for (let i = 1; i <= 5; i++) if (t.skills.includes(i)) kv.push(`skill${i} = true;`);
    kv.push('single = true;', 'coop = true;', 'dm = true;');
    if (t.ambush) kv.push('ambush = true;');
    if (t.dormant) kv.push('dormant = true;');
    t.args.forEach((a, i) => { if (a) kv.push(`arg${i} = ${a};`); });
    out.push(`thing // ${t.cls}\n{\n${kv.map((x) => '  ' + x).join('\n')}\n}`);
  }
  lv.counts = { vertices: verts.length, linedefs: lv.lines.length, sidedefs: sides.length, sectors: lv.sectors.length, things: lv.things.length };
  return out.join('\n') + '\n';
}
