// Builds dist/cosmic-calamity-assault.pk3 from mod/ and checks the asset
// contract (docs/ASSETS.md):
//   - writes mod/mapinfo/doomednums.gen.txt from tools/data/things.json
//   - writes mod/TEXTURES.gen.txt: HUD frames (graphics/hud, XScale 3, grAb
//     offsets) and walls/flats (XScale 2). Wall and flat PNGs are packed under
//     texsrc/ (outside the textures/ and flats/ namespaces) so only the scaled
//     TEXTURES definitions exist in game.
//   - checks every sprite frame used in ZScript states, every texture and
//     thing used in compiled maps, and every sound used in code, and reports
//     what is missing
// Usage: node tools/build.mjs [--strict] [--out dist/x.pk3]
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'node:fs';
import { join, relative, dirname, basename, extname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { pngInfo } from './lib/png.mjs';
import { writeZip } from './lib/zip.mjs';
import { readWad } from './lib/wad.mjs';
import { quantizePNG } from './lib/quant.mjs';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MOD = join(ROOT, 'mod');
const args = process.argv.slice(2);
const STRICT = args.includes('--strict');
// Pack optimisation (source art in mod/ stays truecolour / WAV):
//   sprites + HUD frames → 256-colour indexed PNGs; sounds → OGG Vorbis (if ffmpeg exists)
const QUANT = !args.includes('--no-quantize');
const OGG = !args.includes('--no-ogg') && (() => { try { return execFileSync('ffmpeg', ['-hide_banner', '-encoders'], { stdio: 'pipe' }).toString().includes('libvorbis'); } catch { return false; } })();
const CACHE = join(ROOT, '.gz/cache');
mkdirSync(CACHE, { recursive: true });
function cached(kind, data, fn) {
  const key = createHash('sha1').update(kind).update(data).digest('hex');
  const f = join(CACHE, key);
  if (existsSync(f)) return readFileSync(f);
  const out = fn(data);
  writeFileSync(f, out);
  return out;
}
const oggOf = (wav) => cached('ogg-q3', wav, (d) => {
  const tmpIn = join(CACHE, 'in.wav'), tmpOut = join(CACHE, 'out.ogg');
  writeFileSync(tmpIn, d);
  execFileSync('ffmpeg', ['-y', '-loglevel', 'error', '-i', tmpIn, '-c:a', 'libvorbis', '-q:a', '3', tmpOut]);
  return readFileSync(tmpOut);
});
const OUT = resolve(ROOT, args.includes('--out') ? args[args.indexOf('--out') + 1] : 'dist/cosmic-calamity-assault.pk3');

const walk = (d) => existsSync(d) ? readdirSync(d).flatMap((f) => { const p = join(d, f); return statSync(p).isDirectory() ? walk(p) : [p]; }) : [];
const files = walk(MOD);
const rel = (p) => relative(MOD, p).split('\\').join('/');
const lumpName = (p) => basename(p, extname(p)).toUpperCase();
let problems = [], warnings = [];

// ------------------------------------------------------------------ DoomEdNums
const things = JSON.parse(readFileSync(join(ROOT, 'tools/data/things.json'), 'utf8'));
const ed = Object.entries(things).filter(([k, v]) => !k.startsWith('_') && v.ed && v.ed !== 1);
mkdirSync(join(MOD, 'mapinfo'), { recursive: true });
writeFileSync(join(MOD, 'mapinfo/doomednums.gen.txt'),
  '// GENERATED by tools/build.mjs from tools/data/things.json. Do not edit.\nDoomEdNums\n{\n' +
  ed.map(([k, v]) => `\t${v.ed} = ${v.z || k}`).join('\n') + '\n}\n');

// ------------------------------------------------------------------ TEXTURES
const tex = ['// GENERATED by tools/build.mjs. Do not edit. HUD frames at 3x, walls/flats at 2x.'];
const hud = files.filter((f) => rel(f).startsWith('graphics/hud/') && f.endsWith('.png')).sort();
for (const f of hud) {
  const { w, h, grab } = pngInfo(readFileSync(f));
  const [ox, oy] = grab || [0, 0];
  tex.push(`Sprite "${lumpName(f)}", ${w}, ${h} { XScale 3.0 YScale 3.0 Offset ${ox}, ${oy} Patch "graphics/hud/${basename(f)}", 0, 0 }`);
}
// hi-res graphics (title, menu logo, intermission): 2x, packed outside the graphics namespace
const hires = files.filter((f) => rel(f).startsWith('graphics/hires/') && f.endsWith('.png')).sort();
for (const f of hires) {
  const { w, h } = pngInfo(readFileSync(f));
  tex.push(`Graphic "${lumpName(f)}", ${w}, ${h} { XScale 2.0 YScale 2.0 Patch "texsrc/gfx/${basename(f)}", 0, 0 }`);
}
const walls = files.filter((f) => rel(f).startsWith('textures/') && f.endsWith('.png')).sort();
const flats = files.filter((f) => rel(f).startsWith('flats/') && f.endsWith('.png')).sort();
for (const f of walls) {
  const { w, h } = pngInfo(readFileSync(f));
  tex.push(`WallTexture "${lumpName(f)}", ${w}, ${h} { XScale 2.0 YScale 2.0 WorldPanning Patch "texsrc/walls/${basename(f)}", 0, 0 }`);
}
for (const f of flats) {
  const { w, h } = pngInfo(readFileSync(f));
  tex.push(`Flat "${lumpName(f)}", ${w}, ${h} { XScale 2.0 YScale 2.0 Patch "texsrc/flats/${basename(f)}", 0, 0 }`);
}
writeFileSync(join(MOD, 'TEXTURES.gen.txt'), tex.join('\n') + '\n');

// ------------------------------------------------------------------ contract checks
// sprites available: sprites/**/PPPPF[R][F2R2].png  and graphics/hud/PPPPF0.png
const haveFrame = new Map();   // "PPPP" -> Set of frame letters
const addFrame = (name) => {
  const m = /^([A-Z0-9_]{4})([A-Z\[\]\\])([0-9])(?:([A-Z\[\]\\])([0-9]))?$/.exec(name);
  if (!m) return;
  if (!haveFrame.has(m[1])) haveFrame.set(m[1], new Set());
  haveFrame.get(m[1]).add(m[2]);
  if (m[4]) haveFrame.get(m[1]).add(m[4]);
};
files.filter((f) => rel(f).startsWith('sprites/') && f.endsWith('.png')).forEach((f) => addFrame(lumpName(f)));
hud.forEach((f) => addFrame(lumpName(f)));

// sprite frames referenced by ZScript states
const zs = files.filter((f) => f.endsWith('.zs'));
const needFrames = new Map();  // sprite -> Set(frames) (with where)
const stateLine = /^\s*(?:[A-Za-z_][\w]*:\s*)?([A-Z0-9_]{4})\s+([A-Z\[\]\\#"]+)\s+(-?\d+|\w+\(.*?\))/;
for (const f of zs) {
  const src = readFileSync(f, 'utf8');
  let inStates = false, depth = 0;
  for (const line of src.split('\n')) {
    if (/^\s*States\b/.test(line)) { inStates = true; depth = 0; }
    if (inStates) {
      depth += (line.match(/\{/g) || []).length - (line.match(/\}/g) || []).length;
      const m = stateLine.exec(line);
      if (m && m[1] !== 'TNT1' && !/^(Goto|Loop|Stop|Wait|Fail)$/i.test(m[1])) {
        if (!needFrames.has(m[1])) needFrames.set(m[1], new Set());
        for (const ch of m[2].replace(/"/g, '')) needFrames.get(m[1]).add(ch);
      }
      if (depth <= 0 && line.includes('}')) inStates = false;
    }
  }
}
let missingFrames = [];
for (const [spr, frs] of needFrames) for (const fr of frs) if (!haveFrame.get(spr)?.has(fr)) missingFrames.push(spr + fr);

// images used by name in code (DrawImage / Inventory.Icon / Spawn states already covered)
const imgRefs = new Set();
for (const f of zs) for (const m of readFileSync(f, 'utf8').matchAll(/"((?:IRIS[ITLRAG]\d)|SCOPEMSK|[A-Z0-9]{4}A0)"/g)) imgRefs.add(m[1]);
const haveImg = new Set(files.filter((f) => f.endsWith('.png')).map(lumpName));
const missingImgs = [...imgRefs].filter((n) => !haveImg.has(n));

// maps: textures + thing types
const texNames = new Set([...walls, ...flats].map(lumpName));
const edNums = new Set(Object.values(things).filter((v) => v.ed).map((v) => v.ed));
const maps = files.filter((f) => rel(f).startsWith('maps/') && f.toLowerCase().endsWith('.wad'));
const missingTex = new Set(), badThings = new Set();
for (const f of maps) {
  const wad = readWad(readFileSync(f));
  const tm = wad.lumps.find((l) => l.name === 'TEXTMAP');
  if (!tm) { problems.push(`${rel(f)}: no TEXTMAP`); continue; }
  const txt = tm.data.toString('latin1');
  for (const m of txt.matchAll(/texture(?:top|middle|bottom|floor|ceiling)\s*=\s*"([^"]*)"/gi)) {
    const n = m[1].toUpperCase();
    if (n && n !== '-' && n !== 'F_SKY1' && !texNames.has(n)) missingTex.add(n);
  }
  for (const m of txt.matchAll(/thing\s*(?:\/\/[^\n]*)?\s*\{[^}]*?type\s*=\s*(\d+)/gi)) {
    const t = +m[1];
    if (!edNums.has(t) && t !== 1) badThings.add(`${rel(f)}: type ${t}`);
  }
}

// sounds: every "group/name" used in code must be in SNDINFO
const sndinfo = existsSync(join(MOD, 'SNDINFO.txt')) ? readFileSync(join(MOD, 'SNDINFO.txt'), 'utf8') : '';
const sndDefined = new Set([...sndinfo.matchAll(/^\s*([a-z0-9_]+\/[a-z0-9_]+)\s/gim)].map((m) => m[1].toLowerCase()));
const sndUsed = new Set();
const sndCtx = /(?:Sound|A_StartSound|S_StartSound|DeathSound|SeeSound|PainSound|ActiveSound|AttackSound|MeleeSound|BounceSound|UpSound|PickupSound|FireSound|A_Quake\w*|A_VileAttack|A_CustomMeleeAttack)\b[^;\n]*/g;
for (const f of [...zs, join(MOD, 'MAPINFO.txt')]) {
  if (!existsSync(f)) continue;
  for (const ctx of readFileSync(f, 'utf8').matchAll(sndCtx)) for (const m of ctx[0].matchAll(/"([a-z0-9_]+\/[a-z0-9_]+)"/gi)) if (!m[1].startsWith('music/')) sndUsed.add(m[1].toLowerCase());
}
const missingSnd = [...sndUsed].filter((s) => !sndDefined.has(s) && s !== 'world/quake');

// ------------------------------------------------------------------ report
const rep = (label, list, fatal) => {
  if (!list.length) return;
  const msg = `${label} (${list.length}): ${list.slice(0, 40).join(' ')}${list.length > 40 ? ' ...' : ''}`;
  (fatal ? problems : warnings).push(msg);
};
rep('missing sprite frames', missingFrames.sort(), STRICT);
rep('missing images', missingImgs.sort(), STRICT);
rep('missing map textures', [...missingTex].sort(), STRICT);
rep('unknown thing types', [...badThings], true);
rep('sounds not in SNDINFO', missingSnd.sort(), STRICT);

// While a map is still being built, the episode skips it: each map's Next
// follows the MAPINFO chain to the next map that has a compiled WAD.
function chainBuiltMaps(txt) {
  const have = new Set(existsSync(join(MOD, 'maps')) ? readdirSync(join(MOD, 'maps')).map((f) => f.replace(/\.wad$/i, '').toUpperCase()) : []);
  const next = {};
  for (const m of txt.matchAll(/map\s+(\w+)[^{]*\{[^}]*?Next\s*=\s*"(\w+)"/gi)) next[m[1].toUpperCase()] = m[2];
  return txt.replace(/(map\s+(\w+)[^{]*\{[^}]*?Next\s*=\s*")(\w+)(")/gi, (all, pre, map, nx, post) => {
    let n = nx, guard = 0;
    while (/^MAP\d\d$/i.test(n) && !have.has(n.toUpperCase()) && next[n.toUpperCase()] && guard++ < 20) n = next[n.toUpperCase()];
    if (n !== nx) console.log(`mapinfo: ${map} -> ${n} (${nx} not built yet)`);
    return pre + n + post;
  });
}

// ------------------------------------------------------------------ pack
const entries = [];
const skip = (r) => r.endsWith('.md') || r.startsWith('.');
for (const f of files) {
  let r = rel(f);
  if (skip(r)) continue;
  if (r.startsWith('textures/')) r = 'texsrc/walls/' + r.slice('textures/'.length);
  else if (r.startsWith('flats/')) r = 'texsrc/flats/' + r.slice('flats/'.length);
  else if (r.startsWith('graphics/hires/')) r = 'texsrc/gfx/' + r.slice('graphics/hires/'.length);
  let data = readFileSync(f);
  if (QUANT && f.endsWith('.png') && (r.startsWith('sprites/') || r.startsWith('graphics/hud/'))) {
    const q = cached('quant256', data, quantizePNG);
    if (q.length < data.length) data = q;
  }
  if (OGG && r.startsWith('sounds/') && r.endsWith('.wav')) { data = oggOf(data); r = r.replace(/\.wav$/, '.ogg'); }
  if (r === 'MAPINFO.txt') data = Buffer.from(chainBuiltMaps(data.toString('utf8')));
  entries.push({ name: r, data });
}
// the generated files were written after `files` was listed on a first run
for (const g of ['mapinfo/doomednums.gen.txt', 'TEXTURES.gen.txt']) if (!entries.some((e) => e.name === g)) entries.push({ name: g, data: readFileSync(join(MOD, g)) });
entries.sort((a, b) => a.name.localeCompare(b.name));
mkdirSync(dirname(OUT), { recursive: true });
const zip = writeZip(entries);
writeFileSync(OUT, zip);

const count = (p) => files.filter((f) => rel(f).startsWith(p)).length;
console.log(`pk3: ${relative(ROOT, OUT)} ${(zip.length / 1048576).toFixed(1)} MB, ${entries.length} files ` +
  `(sprites ${count('sprites/')}, hud ${hud.length}, textures ${walls.length}, flats ${flats.length}, sounds ${count('sounds/')}, maps ${maps.length})`);
for (const w of warnings) console.log('warn:', w);
for (const p of problems) console.log('FAIL:', p);
process.exit(problems.length ? 1 : 0);
