version "4.12"

// Cosmic Calamity: Assault — Case File 51. See GAME_DESIGN.md; asset names in docs/ASSETS.md.
#include "zscript/cca/events.zs"
#include "zscript/cca/player.zs"
#include "zscript/cca/weapons/base.zs"
#include "zscript/cca/weapons/human.zs"
#include "zscript/cca/weapons/alien.zs"
#include "zscript/cca/weapons/grenades.zs"
#include "zscript/cca/items.zs"
#include "zscript/cca/monsters.zs"
#include "zscript/cca/npcs.zs"
#include "zscript/cca/world.zs"
#include "zscript/cca/props.zs"
#include "zscript/cca/hud.zs"
#include "zscript/cca/selftest.zs"
#include "zscript/cca/tour.zs"
